version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: fsw-barber-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db:/var/lib/postgresql/data
